### ISSUE TITLE
A simple installation procedure for Windows 10

### ISSUE THREAD

**Issue by KigenHasebe** [MrYsLab/s3onegpio#44]
This is only a suggestion and needs no response.

I hope a simple installation procedure for Windows 10 which do not depend on WSL so that more people use "Scratch3 Extension For GPIO Control".

I finished such a procedure. Now in Windows cmd, I can simply start the Scratch 3 with S3OneGPIO to run Scratch scripts to control Raspi GPIO pins with s3r over WiFi connection.

Surely, the current formal procedure "Creating a Scratch3 Extension For GPIO Control - Part 1" works well for WSL. But WSL is complicated and bothering. WSL may be useful for developmental works on Windows 10. Nevertheless, for that purpose Linux serves far more. In addition, WSL is never necessary for the use of Scratch itself. For traditional Windows 10 users, Power Shell will be more useful than WSL for developmental works.

For a reference, I describe the outline of my procedure which roughly follows the current formal one. It does not use WSL at all and does not use Power Shell in direct.

1. Setting Up A Development Environment

I downloaded all installation files from their original sites with a browser and executed or expanded them only with Windows Explorer.

1-1. Nodejs and npm

https://nodejs.org/

1-2. Yarn

https://classic.yarnpkg.com/

1-3. Git

https://git-scm.com/

1-4. A copy of scratch-vm and scratch-gui

https://github.com/MrYsLab/s3onegpio/

2. Building The Code

I executed all commands in not elevated Windows cmd.

Although the initial installation, I followed the "rebuilding_and_rerunning.txt" of:
https://github.com/MrYsLab/s3onegpio/blob/master/notes/rebuilding_and_rerunning.txt

That's all. It's simple and easy.

About the installation of s3r, I shall write another issue.

My environment is the following: 

Windows 10 Pro 64bit Japanese Version (Version 20H2, build 19042.685)
(a virtual machine in VirtualBox 6.1.16, hosted on Solaris 11.3)

node :	v14.15.
npm :	6.14.10
yarn :	1.22.5
git :	2.30.0.windows.1

By the way, the Japanese national curriculum of Information processing for elementary schools adopted Scratch 3 as one of must educational materials on 2020. I hope that Japanese users of S3OneGPIO will increase with simple installation procedures for Windows and with Japanized Scratch blocks. I regret that in Japan Windows is overwhelmingly dominant but Linux is very minor.

My grandson (13 years old) and I are going to build Scratch scripts to control and self-drive our own toy cars which are based on Raspi. For that purpose, S3OneGPIO is the best and only one programming environment.

Thanks S3OneGPIO!

**Comment by MrYsLab** [comment]
@KigenHasebe 
Thanks very much for taking the time to document this. The reason that I mention using WSL was information from [Hiro Osaki's article](https://medium.com/@hiroyuki.osaki/how-to-develop-your-own-block-for-scratch-3-0-1b5892026421) and from [this link](https://github.com/LLK/scratch-www#windows) from the Scratch GitHub repository. 

As you probably have realized, I do not do any development using a Windows platform and work exclusively in Linux. I do test in Windows, however.  Because of that, I will leave my blog post as is since I am not comfortable debugging Windows development environments.

Again, I appreciate your time. If you have any questions as you interact with the RPi, please don't hesitate to contact me.

I am closing this issue, but if necessary, it can be reopened.
